/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtractionRouteImport } from './routes/extraction'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates_.$candidateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionRoute = ExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/candidates_/$candidateId',
  path: '/candidates/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extraction': typeof ExtractionRoute
  '/settings': typeof SettingsRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extraction': typeof ExtractionRoute
  '/settings': typeof SettingsRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/candidates': typeof CandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extraction': typeof ExtractionRoute
  '/settings': typeof SettingsRoute
  '/candidates_/$candidateId': typeof CandidatesCandidateIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extraction'
    | '/settings'
    | '/candidates/$candidateId'
    | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extraction'
    | '/settings'
    | '/candidates/$candidateId'
    | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/extraction'
    | '/settings'
    | '/candidates_/$candidateId'
    | '/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtractionRoute: typeof ExtractionRoute
  SettingsRoute: typeof SettingsRoute
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraction': {
      id: '/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates_/$candidateId': {
      id: '/candidates_/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtractionRoute: ExtractionRoute,
  SettingsRoute: SettingsRoute,
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
