/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates_.$candidateId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/candidates_/$candidateId',
  path: '/candidates/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/candidates': typeof CandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidates_/$candidateId': typeof CandidatesCandidateIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidates/$candidateId' | '/jobs/$jobId' | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidates/$candidateId' | '/jobs/$jobId' | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/candidates_/$candidateId'
    | '/jobs/$jobId'
    | '/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates_/$candidateId': {
      id: '/candidates_/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
